<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ozobot" nsURI="http://www.example.org/ozobot" nsPrefix="ozobot">
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Area">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x_size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y_size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ozobot">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x_pos" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y_pos" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="z_pos" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Command"/>
  <eClassifiers xsi:type="ecore:EClass" name="Move"/>
  <eClassifiers xsi:type="ecore:EClass" name="Rotate"/>
  <eClassifiers xsi:type="ecore:EClass" name="Light"/>
  <eClassifiers xsi:type="ecore:EClass" name="Wait"/>
  <eClassifiers xsi:type="ecore:EClass" name="Start"/>
  <eClassifiers xsi:type="ecore:EClass" name="End"/>
  <eClassifiers xsi:type="ecore:EClass" name="Transition"/>
</ecore:EPackage>
